project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!data/gym_data/*"

website:
  title: "Zach Loo"
  favicon: media/ZL_favi_final.png
  navbar:
    title: false
    logo: media/ZL_favi_final.png
    left:
      - text: "About"
        href: about.qmd
      - text: "Curriculum Vitae"
        href: vitae.qmd
      - text: "The Blog"
        href: posts.qmd
  page-footer: 
    right: This website is built with Quarto and GitHub Pages.

format:
  html:
    theme: 
      - minty
      - styles.scss
    mainfont: Cormorant Garamond
    css: styles.css
    toc: true
    page-layout: full

editor: source

